version: '3.8'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: export-endpoint
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 161int
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: